-- PRODUCT 더미데이터 INSERT 구문

--행 1
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'mStone Groove T 풀윤활 퍼플러 (은축, 45g)',157000,'엠스톤1','image1','image2','image3','image4',1,10000);
--행 2
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'mStone Groove T 풀윤활 실리콘 클라리온2 (저소음 적축, 35g)',157000,'엠스톤2','image1','image2','image3','image4',1,10000);
--행 3
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'엠스톤 Rooky 68BT RGB (후아노 청축)',62000,'엠스톤3','image1','image2','image3','image4',1,10000);
--행 4
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'mStone Groove T 풀윤활 다크그레이 (적축, 35g)',149000,'엠스톤4','image1','image2','image3','image4',1,10000);
--행 5
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'mStone Groove F 풀윤활 클라리온S(갈축,45g)',151000,'엠스톤5','image1','image2','image3','image4',1,10000);
--행 6
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'엠스톤 Groove T 풀윤활 라이트MA (코랄축, 38g)',149000,'엠스톤6','image1','image2','image3','image4',1,10000);
--행 7
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'mStone Groove T 풀윤활 라이트그레이 (밀키축, 45g)',159000,'엠스톤7','image1','image2','image3','image4',1,10000);
--행 8
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'K660M TKL 체리키보드',142000,'앱코1','image1','image2','image3','image4',1,10001);
--행 9
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'K641 SLIM PLUS RGB 게이밍 기계식 키보드',62000,'앱코2','image1','image2','image3','image4',1,10001);
--행 10
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'TOS180 블루투스 펜타그래프 키보드',38500,'앱코3','image1','image2','image3','image4',1,10001);
--행 11
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'KN01C PBT RGB 무접점 게이밍',155000,'앱코4','image1','image2','image3','image4',1,10001);
--행 12
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'TW1867 레트로 블루투스 기계식',98000,'앱코5','image1','image2','image3','image4',1,10001);
--행 13
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'AN50 아이스큐브 무빙 LED 광축 게이밍 키보드',117000,'앱코6','image1','image2','image3','image4',1,10001);
--행 14
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'KN10C PBT RGB 무접점 게이밍',210000,'앱코7','image1','image2','image3','image4',1,10001);
--행 15
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'FC750R PD 화이트 민트 한글',147000.0,'레오폴드1','image1','image2','image3','image4',1,10004);
--행 16
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'FC900R PD 스웨디시 화이트 한글',149500.0,'레오폴드2','image1','image2','image3','image4',1,10004);
--행 17
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'iKBC CD-108 염료승화인쇄 한글',107000.0,'레오폴드3','image1','image2','image3','image4',1,10004);
--행 18
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'FC980C 영문 블랙 45g 균등',260000.0,'레오폴드4','image1','image2','image3','image4',1,10004);
--행 19
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'FC650MDSBT PD 그레이블루 영문',154000.0,'레오폴드5','image1','image2','image3','image4',1,10004);
--행 20
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'FC210TP PD 블랙',49000.0,'레오폴드6','image1','image2','image3','image4',1,10004);
--행 21
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'FC750R PD 그레이 블루 한글',150000.0,'레오폴드7','image1','image2','image3','image4',1,10004);
--행 22
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'닌자87 풀윤활 키보드 RGB 저소음 스위치 기계식 화이트K레인보우 후아노 적축',113000.0,'몬스타기어1','image1','image2','image3','image4',1,10003);
--행 23
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'닌자87BT 풀윤활 퀵스왑 기계식 커스텀키보드 블랙 게이트론',155000.0,'몬스타기어2','image1','image2','image3','image4',1,10003);
--행 24
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'닌자87PRO 풀윤활 RGB 저소음 스위치 기계식 커스텀키보드 퍼플B퍼플레빗 Durock T1',159000.0,'몬스타기어3','image1','image2','image3','image4',1,10003);
--행 25
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'닌자87PRO 풀윤활 RGB 퀵스왑 기계식 커스텀키보드 화이트B퍼플레빗 Durock T1',159000.0,'몬스타기어4','image1','image2','image3','image4',1,10003);
--행 26
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'Melgeek Mojo68 유무선 블루투스5.2 2.4무선 커스텀 키보드',262000.0,'몬스타기어5','image1','image2','image3','image4',1,10003);
--행 27
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'닌자87PRO S RGB 저소음축 퀵스왑 기계식 커스텀키보드',110000.0,'몬스타기어6','image1','image2','image3','image4',1,10003);
--행 28
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'닌자87BT 게이트론 갈축 블루투스 5.0 기계식 유무선 커스텀키보드',99000.0,'몬스타기어7','image1','image2','image3','image4',1,10003);
--행 29
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'TFG ART Wireless V2 듀얼무선 기계식 키보드',177000.0,'한성컴퓨터1','image1','image2','image3','image4',1,10002);
--행 30
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'GK898B 염료승화 EDITION 무접점 키보드',185000.0,'한성컴퓨터2','image1','image2','image3','image4',1,10002);
--행 31
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'GK893B SPORTS 한글',159000.0,'한성컴퓨터3','image1','image2','image3','image4',1,10002);
--행 32
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'Gtune GK787 OfficeMaster PBT 체리 게이밍 기계식',186000.0,'한성컴퓨터4','image1','image2','image3','image4',1,10002);
--행 33
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'GK993B SKY 블루투스 기계식 키보드 한글',129000.0,'한성컴퓨터5','image1','image2','image3','image4',1,10002);
--행 34
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'TFG ARF 체리 게이밍 기계식 한글',89000.0,'한성컴퓨터6','image1','image2','image3','image4',1,10002);
--행 35
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_NAME, PRICE, DESCRIPTION, ATTACHMENT1, ATTACHMENT2, ATTACHMENT3, ATTACHMENT4, PRODUCT_STATUS, SELLER_NO) VALUES (SEQ_PRODUCT_NO.NEXTVAL,'GK888B minicoup',169000.0,'한성컴퓨터7','image1','image2','image3','image4',1,10002);

COMMIT;